baseURL = 'https://chapien.net/'
languageCode = 'en-us'
title = 'The Claire Scrolls'
copyright = "Copyright © 2025 by Claire. Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/#?)"
theme = 'blue'
disableKinds = ['taxonomy']

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = true
    startLevel = 1

[module]
  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"
  [[module.imports]]
    path = "blue"

[outputs]
home = ['html']
section = ['html']
taxonomy = ['html']
term = ['html']

[taxonomies]
series = 'series'
tag = 'tags'
arttag = 'arttags'
category = 'categories'

[permalinks]
tags = 'blog/tags/:title'
arttags = 'art/tags/:title'
series = 'blog/series/:title'
blog = 'blog/:year/:title'

[[menu.main]]
name = 'Home'
url = ''
weight = -1
params.img = 'icons/home.svg'

[[menu.main]]
name = "About"
url = "about"
weight = 10
params.img = 'icons/about.svg'

[[menu.main]]
name = "Contact"
url = "contact"
weight = 15
params.img = 'icons/contact.svg'

[[menu.main]]
name = "Blog"
url = "blog"
weight = 3
params.img = 'icons/blog.svg'

[[menu.main]]
name = "Art"
url = "art"
weight = 4
params.img = 'icons/art.svg'

[[menu.main]]
name = "Guestbook"
url = "guestbook"
weight = 9
params.img = "icons/guestbook.svg"

[[menu.socials]]
name = "Pronouns"
url = "https://en.pronouns.page/@chapien"
weight = -1
params.img = 'icons/pronouns.svg'

[[menu.socials]]
name = "itch.io"
url = "https://chapien.itch.io/"
weight = 1
params.img = "icons/itchio.svg"

[[menu.socials]]
name = "ko-fi"
url = "https://ko-fi.com/chapien"
weight = 2
params.img = "icons/kofi.svg"

[[menu.socials]]
name = "Github"
url = "https://github.com/Chapien"
weight = 3
params.img = "icons/github.svg"

[[menu.socials]]
name = "Bluesky"
url = "https://bsky.app/profile/claire.chapien.net"
weight = 4
params.img = 'icons/bluesky.svg'

[[menu.socials]]
name = "Tumblr"
url = "https://chappydev.tumblr.com/"
weight = 5
params.img = "icons/tumblr.svg"

[[menu.socials]]
name = "Mastodon"
url = "https://tech.lgbt/@chapien"
weight = 6
params.img = "icons/mastodon.svg"

[[menu.socials]]
name = "Bookwyrm"
url = "https://bookwyrm.social/user/chapien"
weight = 7
params.img = "icons/bookwyrm.svg"

[[menu.socials]]
name = "RSS"
url = "/blog/feed.xml"
weight = 10
params.img = 'icons/rss.svg'

[[menu.footer]]
name = "About"
url = "about"
weight = -1

[[menu.footer]]
name = "Source Code"
url = "https://github.com/Chapien/chapien.github.io"
weight = 1

[params]
env = "production"
hcard = true
description = "Claire's personal blog."
issoURL = 'comments.chapien.net'
profilePicture = "images/profile.png"
related = false
voting = false
hideExternalMenu = true
noData = true
fontSwap = true

[params.author]
name = 'Claire'
email = 'inquiries@chapien.net'
nickname = 'chapien'
pronouns = ['She', 'Her']

[params.art]
takesCommissions = false
commissionsOpen = false
statsPage = false
galleries = ["art/goblinsona"]