### Base Hugo ##########################################################

baseURL = "https://chapien.net/"
languageCode = "en-us"
title = "Claire's Blog"
copyright = "Website content Copyright © 2025 by Claire is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
theme = "hugo-PaperMod"

### Languages ##########################################################

[languages.en]
languageName = "English"
weight = 1

[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.en.menu.main]]
name = "About"
url = "about"
weight = 1

[[languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 4

[[languages.en.menu.main]]
name = "Archive"
url = "archive"
weight = 5

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 15

### Papermod Params ####################################################

[params]
home = ["HTML","RSS","JSON"]
env = "production"
hcard = true
description = "Claire's personal blog."
author = "Claire"
Nickname="chapien"
Pronouns= ["She","Her"]
defaultTheme = "auto"
CanonicalLinkText = " "
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowAllPagesInArchive = false
ShowPageNums = true
ShowToC = true
TocOpen = true
socialIcons = [
    {name = "itchio", url = "https://itch.io/profile/chapien"},
    {name = "kofi", url = "https://ko-fi.com/chapien"},    
    {name = "github", url = "https://github.com/Chapien"},
    {name = "lastfm", url = "https://www.last.fm/user/chapien"},
    {name = "bookwyrm", url = "https://bookwyrm.social/user/chapien"},
    {name = "bluesky", url = "https://bsky.app/profile/claire.chapien.net"},
    {name = "tumblr", url = "https://chappydev.tumblr.com/"},
    {name = "mastodon", url = "https://transfem.social/@chapien"},
]

[params.homeInfoParams]
Title = "Claire's Blog"
Content = "Short stories. Blogs about mental health, game dev, and LGBTQ+ issues. [More information](about)."
imageURL = "assets/images/profile.png"
AlignSocialIconsTo = "Center"
buttons = [
    {name = "About", url = "about"},
    {name = "Contact", url = "contact"},
    {name = "Blog", url = "/blog"}
]


#[params.profileMode]
#enabled = true
