baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Claire Scrolls'
theme = ['hugo-redirect', 'blue']
disableKinds = ['taxonomy']

[module]
  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"
  [[module.imports]]
    path = "blue"

[outputs]
home = ['html']
section = ['html']
taxonomy = ['html']
term = ['html']

[taxonomies]
series = 'series'
tag = 'tags'
category = 'categories'

[permalinks]
tags = 'blog/tags/:title'
series = 'blog/series/:title'
bolg = 'blog/:year/:title'

[[menu.main]]
name = 'Home'
url = ''
weight = -1

[[menu.main]]
name = "About"
url = "about"
weight = 1

[[menu.main]]
name = "Contact"
url = "contact"
weight = 2

[[menu.main]]
name = "Blog"
url = "blog"
weight = 3

[params]
author = 'Claire'
description = 'Weh'
isso_url = 'comments.chapien.net'
profile_picture = "profile.png"

